### PR TITLE
role component from Account Page UI added

### PR DESCRIPTION
**Pull request by AryaMane1210**

### CODE REVIEW

**Comment by codebyviral** [comment]
Please rename component file. Naming in react (vite) environment => first letter should be capital

**Comment by AryaMane1210** [comment]
i made the changes, can you please check and lmk if it is done?

**Comment by codebyviral** [comment]
Please rename component file. Naming in react (vite) environment => first letter should be capital

**Comment by codebyviral** [comment]
@AryaMane1210 It'll be AdminTask component so rename your file kindly. We don't need to edit existing Task.js

**Review by codebyviral — APPROVED** [review]
Approved 🆗

**Pull request merged**
